local M = {}

local function esc(value)
    return tostring(value or ""):gsub("|", "\\|"):gsub("\n", " ")
end

local function get_keymaps()
    local ok, maps = pcall(vim.api.nvim_get_keymap, "")
    if not ok then
        return {}
    end

    table.sort(maps, function(a, b)
        if a.mode == b.mode then
            return (a.lhs or "") < (b.lhs or "")
        end
        return (a.mode or "") < (b.mode or "")
    end)

    return maps
end

local function get_commands()
    local ok, commands = pcall(vim.api.nvim_get_commands, { builtin = false })
    if not ok then
        return {}
    end

    local result = {}
    for name, command in pairs(commands) do
        table.insert(result, {
            name = name,
            desc = command.desc or command.definition or "",
        })
    end

    table.sort(result, function(a, b)
        return a.name < b.name
    end)

    return result
end

local function get_lazy_stats()
    local ok, lazy = pcall(require, "lazy")
    if not ok then
        return nil
    end

    local ok_stats, stats = pcall(lazy.stats)
    if not ok_stats then
        return nil
    end

    return stats
end

local function generate_lines()
    local version = vim.version()
    local lines = {
        "# Elite Neovim IDE — Live Cheatsheet",
        "",
        "> Generated from the running Neovim environment. Do not edit this file manually.",
        "",
        "## Quick discovery",
        "",
        "| Action | How |",
        "| --- | --- |",
        "| Show all keybindings | `<leader>?` |",
        "| Search keymaps | `<leader>fk` |",
        "| Search and run Ex commands | `<leader>fc` |",
        "| Open this cheatsheet | `<leader>fC` or `:Cheatsheet` |",
        "| Force regeneration | `:CheatsheetUpdate` |",
        "| Check your setup | `:checkhealth elite` |",
        "| How this config was installed | `:EliteInfo` |",
        "| Built-in Neovim/Vim documentation | `:help` |",
        "| Search built-in documentation | `<leader>fh` |",
        "",
        "## Leader namespaces",
        "",
        "| Key | Group |",
        "| --- | --- |",
    }

    for _, group in ipairs(require("config.leader_groups").groups) do
        table.insert(lines, string.format(
            "| `<leader>%s` | %s |",
            group.key,
            esc(group.label)
        ))
    end

    table.insert(lines, "")
    table.insert(lines, "## Registered keymaps")
    table.insert(lines, "")
    table.insert(lines, "| Mode | Key | Description |")
    table.insert(lines, "| --- | --- | --- |")

    for _, map in ipairs(get_keymaps()) do
        if map.lhs and map.lhs ~= "" then
            table.insert(lines, string.format(
                "| `%s` | `%s` | %s |",
                esc(map.mode),
                esc(map.lhs),
                esc(map.desc or "")
            ))
        end
    end

    table.insert(lines, "")
    table.insert(lines, "## User/plugin Ex commands")
    table.insert(lines, "")
    table.insert(lines, "| Command | Description |")
    table.insert(lines, "| --- | --- |")

    for _, command in ipairs(get_commands()) do
        table.insert(lines, string.format(
            "| `:%s` | %s |",
            esc(command.name),
            esc(command.desc)
        ))
    end

    table.insert(lines, "")
    table.insert(lines, "## Environment")
    table.insert(lines, "")
    table.insert(lines, "| Item | Value |")
    table.insert(lines, "| --- | --- |")
    table.insert(lines, string.format("| Neovim | `%d.%d.%d` |", version.major, version.minor, version.patch))
    table.insert(lines, string.format("| Config | `%s` |", vim.fn.stdpath("config")))
    table.insert(lines, string.format("| Data | `%s` |", vim.fn.stdpath("data")))

    local stats = get_lazy_stats()
    if stats then
        table.insert(lines, string.format(
            "| Lazy plugins | `%d loaded / %d total` |",
            stats.loaded or 0,
            stats.count or 0
        ))
    end

    local clients = vim.lsp.get_clients()
    table.insert(lines, "")
    table.insert(lines, "## LSP servers currently attached")
    table.insert(lines, "")
    if #clients == 0 then
        table.insert(lines, "No LSP clients are currently attached.")
    else
        table.insert(lines, "| Server | Root |")
        table.insert(lines, "| --- | --- |")
        for _, client in ipairs(clients) do
            table.insert(lines, string.format(
                "| `%s` | `%s` |",
                esc(client.name),
                esc(client.root_dir or "")
            ))
        end
    end

    table.insert(lines, "")
    table.insert(lines, "## Built-in documentation")
    table.insert(lines, "")
    table.insert(lines,
        "The complete built-in Vim/Neovim command and key documentation is intentionally not copied into this generated file.")
    table.insert(lines, "Use `:help`, `:help index`, `:help normal-index`, `:help insert-index`, and `:help :commands`.")
    table.insert(lines, "This keeps the generated sheet focused on what this particular environment adds and configures.")

    return lines
end

-- The cheatsheet lives in Neovim's state folder, not in the repo: it contains
-- machine-specific paths and changes on every start, which would keep git dirty.
function M.path()
    return vim.fn.stdpath("state") .. "/cheatsheet.md"
end

function M.generate()
    local path = M.path()
    vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")

    local file = assert(io.open(path, "w"))
    file:write(table.concat(generate_lines(), "\n"))
    file:write("\n")
    file:close()

    return path
end

function M.setup()
    if vim.g.elite_cheatsheet_setup then
        return
    end
    vim.g.elite_cheatsheet_setup = true

    vim.api.nvim_create_user_command("Cheatsheet", function()
        local path = M.generate()
        vim.cmd("edit " .. vim.fn.fnameescape(path))
    end, { desc = "Open live Neovim cheatsheet" })

    vim.api.nvim_create_user_command("CheatsheetUpdate", function()
        local path = M.generate()
        vim.notify("Cheatsheet updated: " .. path)
    end, { desc = "Regenerate live Neovim cheatsheet" })

    vim.api.nvim_create_autocmd("User", {
        pattern = "LazyDone",
        callback = function()
            pcall(M.generate)
        end,
    })

    vim.api.nvim_create_autocmd("BufWritePost", {
        pattern = "*.lua",
        callback = function(args)
            local cfg = vim.fn.stdpath("config")
            local config = (vim.uv.fs_realpath(cfg) or cfg) .. "/"
            local file = vim.uv.fs_realpath(args.file) or args.file

            if file:sub(1, #config) == config then
                vim.defer_fn(function() pcall(M.generate) end, 100)
            end
        end,
    })

    pcall(M.generate)
end

return M
